name: Run workflow for PR
on:
  pull_request:
    branches:
      - jira_test
    types:
      - closed
jobs:
  Run_Selected_Tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: SET Pull Request and ENV Information
        run: |
          python3 os_env_test.py
          echo $MY_VARIABLE
